login:
    path: /login
    controller: App\Controller\LoginController::index

test:
    path: /test
    controller: App\Controller\TestController::index

admin:
    path: /dashboard
    controller: App\Controller\DashboardController::index
